import express from'express';import crypto from'crypto';import path from'path';import{fileURLToPath}from'url';import{initDb,getDb}from'./db.js';import{site}from'../src/config.js';
const app=express(),root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');app.use(express.json({limit:'512kb'}));
const secret=()=>process.env.ADMIN_SESSION_SECRET||'change-this-in-render';const token=(email)=>crypto.createHmac('sha256',secret()).update(email).digest('hex');const cookie=(req)=>{const c=req.headers.cookie||'',m=c.match(/nexora_admin=([^;]+)/);return m?.[1]};const auth=req=>cookie(req)===token(process.env.ADMIN_EMAIL||'admin@nexora.local');
async function store(){await initDb();const d=getDb();const r=await d.execute('SELECT data_json FROM store_content WHERE id=1');if(r.rows.length)return JSON.parse(r.rows[0].data_json);const data={...site,landing:{hero:{image:site.collections[0].image,video:'',badge:'NEW SEASON · 2026',title:'Quietly distinct.',subtitle:'Modern essentials for a wardrobe with intention.',primary:'Explore the collection',secondary:'Shop new in'},story:{heading:'Fewer, better things.',text:'Thoughtful proportions, tactile fabrics and repeat wear.',image:site.products[0].image,stats:[['06','Core pieces'],['04','Collections'],['01','Point of view']]},collections:site.collections,journal:[],testimonials:[],newsletter:{heading:'The occasional email worth opening.',text:'New drops, considered edits and private offers. No noise.'},footer:{description:site.tagline,copyright:'© 2026 Nexora Web'},social:{instagram:'',facebook:'',tiktok:'',whatsapp:''},contact:{messenger:'',whatsapp:''}},seo:{title:'Nexora Web — Modern fashion, considered.',description:'A considered destination for modern wardrobes.',ogImage:'',favicon:'',canonical:''}};await d.execute({sql:'INSERT INTO store_content(id,data_json,updated_at) VALUES(1,?,?)',args:[JSON.stringify(data),new Date().toISOString()]});return data}
app.get('/api/health',async(_,res)=>{try{await initDb();res.json({ok:true})}catch{res.status(503).json({ok:false})}});
app.get('/api/store',async(_,res)=>{try{const d=await store();const db=getDb();const rr=await db.execute('SELECT id,name,review,image,rating FROM reviews ORDER BY id DESC');d.landing.testimonials=rr.rows;res.json(d)}catch{res.status(503).json({error:'Store unavailable'})}});
app.post('/api/orders',async(req,res)=>{const{x}=req.body||{};const{name,email,phone='',address,items,total}=req.body||{};if(!name||!email||!address||!Array.isArray(items)||!items.length||!Number.isInteger(total))return res.status(400).json({error:'Complete checkout details are required.'});if(!/^\S+@\S+\.\S+$/.test(email))return res.status(400).json({error:'Invalid email.'});try{await initDb();await getDb().execute({sql:'INSERT INTO orders(customer_name,email,phone,address,items_json,total,created_at) VALUES(?,?,?,?,?,?,?)',args:[String(name).slice(0,120),String(email).slice(0,180),String(phone).slice(0,40),String(address).slice(0,500),JSON.stringify(items).slice(0,20000),total,new Date().toISOString()]});res.status(201).json({ok:true})}catch{res.status(503).json({error:'Checkout unavailable.'})}});
app.post('/api/subscribe',async(req,res)=>{const email=String(req.body?.email||'');if(!/^\S+@\S+\.\S+$/.test(email))return res.status(400).json({error:'Enter a valid email.'});try{await initDb();await getDb().execute({sql:'INSERT OR IGNORE INTO subscribers(email,created_at) VALUES(?,?)',args:[email,new Date().toISOString()]});res.status(201).json({ok:true})}catch{res.status(503).json({error:'Newsletter unavailable.'})}});
app.post('/api/admin/login',async(req,res)=>{const{email,password}=req.body||{};if(email!==process.env.ADMIN_EMAIL||password!==process.env.ADMIN_PASSWORD)return res.status(401).json({error:'Invalid admin credentials.'});res.setHeader('Set-Cookie',`nexora_admin=${token(email)}; HttpOnly; Path=/; SameSite=Lax; Max-Age=28800`);res.json({ok:true})});
app.get('/api/admin/me',(req,res)=>res.status(auth(req)?200:401).json({ok:auth(req)}));app.post('/api/admin/logout',(req,res)=>{res.setHeader('Set-Cookie','nexora_admin=; HttpOnly; Path=/; Max-Age=0');res.json({ok:true})});
app.get('/api/admin/store',async(req,res)=>{if(!auth(req))return res.status(401).end();res.json(await store())});
app.put('/api/admin/store',async(req,res)=>{if(!auth(req))return res.status(401).end();try{await initDb();await getDb().execute({sql:'INSERT INTO store_content(id,data_json,updated_at) VALUES(1,?,?) ON CONFLICT(id) DO UPDATE SET data_json=excluded.data_json,updated_at=excluded.updated_at',args:[JSON.stringify(req.body),new Date().toISOString()]});res.json({ok:true})}catch{res.status(500).json({error:'Save failed'})}});
app.get('/api/admin/orders',async(req,res)=>{if(!auth(req))return res.status(401).end();const r=await getDb().execute('SELECT * FROM orders ORDER BY id DESC');res.json({orders:r.rows})});app.patch('/api/admin/orders/:id',async(req,res)=>{if(!auth(req))return res.status(401).end();const s=String(req.body?.status||'pending');await getDb().execute({sql:'UPDATE orders SET status=? WHERE id=?',args:[s,Number(req.params.id)]});res.json({ok:true})});
app.get('/api/admin/reviews',async(req,res)=>{if(!auth(req))return res.status(401).end();const r=await getDb().execute('SELECT * FROM reviews ORDER BY id DESC');res.json({reviews:r.rows})});app.post('/api/admin/reviews',async(req,res)=>{if(!auth(req))return res.status(401).end();const{name,review,image='',rating=5}=req.body||{};if(!name||!review)return res.status(400).json({error:'Name and review required'});await getDb().execute({sql:'INSERT INTO reviews(name,review,image,rating,created_at) VALUES(?,?,?,?,?)',args:[String(name).slice(0,100),String(review).slice(0,1000),String(image).slice(0,1000),Math.min(5,Math.max(1,Number(rating)||5)),new Date().toISOString()]});res.json({ok:true})});app.delete('/api/admin/reviews/:id',async(req,res)=>{if(!auth(req))return res.status(401).end();await getDb().execute({sql:'DELETE FROM reviews WHERE id=?',args:[Number(req.params.id)]});res.json({ok:true})});
app.use(express.static(path.join(root,'dist')));app.get('/admin',(_,res)=>res.sendFile(path.join(root,'dist','index.html')));app.get('/landing',(_,res)=>res.sendFile(path.join(root,'dist','index.html')));app.get('/{*splat}',(_,res)=>res.sendFile(path.join(root,'dist','index.html')));app.listen(process.env.PORT||10000);