import express from'express';import path from'path';import{fileURLToPath}from'url';import crypto from'crypto';import{initDb,getDb,defaultLanding}from'./db.js';
const app=express(),root=path.dirname(fileURLToPath(import.meta.url));app.use(express.json({limit:'2mb'}));const now=()=>new Date().toISOString();const safe=(v,n)=>String(v??'').trim().slice(0,n);
function token(email){if(!process.env.ADMIN_SESSION_SECRET)throw new Error('ADMIN_SESSION_SECRET is required');return crypto.createHmac('sha256',process.env.ADMIN_SESSION_SECRET).update(email).digest('hex')}
function auth(req){const c=req.headers.cookie||'',m=c.match(/(?:^|;)\\s*nexora_admin=([^;]+)/);return !!m&&m[1]===token(process.env.ADMIN_EMAIL||'')}
async function store(){await initDb();const r=await getDb().execute('SELECT data_json FROM store_content WHERE id=1');return r.rows[0]?JSON.parse(r.rows[0].data_json):{brand:'Nexora Web',products:[],collections:[],contact:{}}}
function normalize(x){const d=JSON.parse(JSON.stringify(defaultLanding));if(!x||typeof x!=='object')return d;for(const k of Object.keys(d))if(x[k]!==undefined)d[k]=x[k];d.settings={...defaultLanding.settings,...(x.settings||{})};d.navigation={...defaultLanding.navigation,...(x.navigation||{})};d.hero={...defaultLanding.hero,...(x.hero||{})};d.social={...defaultLanding.social,...(x.social||{})};d.contact={...defaultLanding.contact,...(x.contact||{})};d.footer={...defaultLanding.footer,...(x.footer||{})};d.seo={...defaultLanding.seo,...(x.seo||{})};d.design={...defaultLanding.design,...(x.design||{})};d.ai={...defaultLanding.ai,...(x.ai||{})};d.sections=Array.isArray(x.sections)?x.sections.map(s=>({...s,enabled:s.enabled!==false})):d.sections;d.collections=Array.isArray(x.collections)?x.collections.slice(0,30):[];d.journal=Array.isArray(x.journal)?x.journal.slice(0,30):[];d.products=Array.isArray(x.products)?x.products.slice(0,100):[];return d}
app.get('/api/health',(_,res)=>res.json({ok:true}));app.get('/api/store',async(_,res)=>{try{res.json(await store())}catch{res.status(503).json({error:'Store unavailable'})}});
app.get('/api/landing',async(_,res)=>{try{await initDb();const r=await getDb().execute('SELECT published_json FROM landing_content WHERE id=1');const d=r.rows[0]?JSON.parse(r.rows[0].published_json):defaultLanding;const rr=await getDb().execute('SELECT id,name,review,image,rating,created_at FROM reviews ORDER BY id DESC');d.reviews=rr.rows;res.set('Cache-Control','no-store');res.json(d)}catch{res.status(503).json({error:'Landing unavailable'})}});
app.post('/api/orders',async(req,res)=>{const{name,email,phone='',address,items}=req.body||{};if(!name||!email||!address||!Array.isArray(items)||!items.length)return res.status(400).json({error:'Complete checkout details are required.'});if(!/^\\S+@\\S+\\.\\S+$/.test(email))return res.status(400).json({error:'Invalid email.'});try{const s=await store(),catalog=new Map((s.products||[]).map(p=>[String(p.id),p]));let total=0;const clean=items.map(i=>{const p=catalog.get(String(i.id));const qty=Math.max(1,Math.min(20,Number(i.qty)||1));if(!p)throw Error('A selected product is unavailable.');total+=Number(p.price||0)*qty;return{id:p.id,name:p.name,price:Number(p.price||0),qty}});await getDb().execute({sql:'INSERT INTO orders(customer_name,email,phone,address,items_json,total,created_at) VALUES(?,?,?,?,?,?,?)',args:[safe(name,120),safe(email,180),safe(phone,40),safe(address,500),JSON.stringify(clean),total,now()]});res.status(201).json({ok:true})}catch(e){res.status(400).json({error:e.message||'Checkout unavailable.'})}});
app.post('/api/subscribe',async(req,res)=>{const email=safe(req.body?.email,180);if(!/^\\S+@\\S+\\.\\S+$/.test(email))return res.status(400).json({error:'Enter a valid email.'});try{await initDb();await getDb().execute({sql:'INSERT OR IGNORE INTO subscribers(email,created_at) VALUES(?,?)',args:[email,now()]});res.status(201).json({ok:true})}catch{res.status(503).json({error:'Newsletter unavailable.'})}});
app.post('/api/admin/login',async(req,res)=>{const{email,password}=req.body||{};if(!process.env.ADMIN_EMAIL||!process.env.ADMIN_PASSWORD||email!==process.env.ADMIN_EMAIL||password!==process.env.ADMIN_PASSWORD)return res.status(401).json({error:'Invalid admin credentials.'});res.setHeader('Set-Cookie','nexora_admin='+token(email)+'; HttpOnly; Path=/; SameSite=Lax; Max-Age=28800');res.json({ok:true})});
app.get('/api/admin/me',(req,res)=>res.status(auth(req)?200:401).json({ok:auth(req)}));app.post('/api/admin/logout',(req,res)=>{res.setHeader('Set-Cookie','nexora_admin=; HttpOnly; Path=/; Max-Age=0');res.json({ok:true})});
app.get('/api/admin/landing',async(req,res)=>{if(!auth(req))return res.status(401).end();try{await initDb();const r=await getDb().execute('SELECT data_json,published_json,updated_at,published_at FROM landing_content WHERE id=1'),x=r.rows[0];res.json({draft:JSON.parse(x.data_json),published:JSON.parse(x.published_json),updatedAt:x.updated_at,publishedAt:x.published_at})}catch{res.status(500).json({error:'CMS unavailable'})}});
app.put('/api/admin/landing',async(req,res)=>{if(!auth(req))return res.status(401).end();try{const d=normalize(req.body);await initDb();await getDb().execute({sql:'UPDATE landing_content SET data_json=?,updated_at=? WHERE id=1',args:[JSON.stringify(d),now()]});res.json({ok:true,draft:d})}catch{res.status(400).json({error:'Save failed'})}});
app.post('/api/admin/landing/publish',async(req,res)=>{if(!auth(req))return res.status(401).end();try{await initDb();const r=await getDb().execute('SELECT data_json FROM landing_content WHERE id=1');const d=normalize(JSON.parse(r.rows[0].data_json));await getDb().execute({sql:'UPDATE landing_content SET data_json=?,published_json=?,updated_at=?,published_at=? WHERE id=1',args:[JSON.stringify(d),JSON.stringify(d),now(),now()]});res.json({ok:true,published:d})}catch{res.status(500).json({error:'Publish failed'})}});
app.get('/api/admin/store',async(req,res)=>{if(!auth(req))return res.status(401).end();res.json(await store())});app.put('/api/admin/store',async(req,res)=>{if(!auth(req))return res.status(401).end();try{await initDb();await getDb().execute({sql:'INSERT INTO store_content(id,data_json,updated_at) VALUES(1,?,?) ON CONFLICT(id) DO UPDATE SET data_json=excluded.data_json,updated_at=excluded.updated_at',args:[JSON.stringify(req.body),now()]});res.json({ok:true})}catch{res.status(500).json({error:'Save failed'})}});
app.get('/api/admin/orders',async(req,res)=>{if(!auth(req))return res.status(401).end();await initDb();const r=await getDb().execute('SELECT * FROM orders ORDER BY id DESC');res.json({orders:r.rows})});app.patch('/api/admin/orders/:id',async(req,res)=>{if(!auth(req))return res.status(401).end();const s=String(req.body?.status||'pending');if(!['pending','confirmed','packed','shipped','delivered','cancelled'].includes(s))return res.status(400).json({error:'Invalid order status'});await initDb();await getDb().execute({sql:'UPDATE orders SET status=? WHERE id=?',args:[s,Number(req.params.id)]});res.json({ok:true})});
app.get('/api/admin/reviews',async(req,res)=>{if(!auth(req))return res.status(401).end();await initDb();const r=await getDb().execute('SELECT * FROM reviews ORDER BY id DESC');res.json({reviews:r.rows})});app.post('/api/admin/reviews',async(req,res)=>{if(!auth(req))return res.status(401).end();const{name,review,image='',rating=5}=req.body||{},n=safe(name,100),v=safe(review,1500),rate=Math.min(5,Math.max(1,Number(rating)||5));if(!n||!v)return res.status(400).json({error:'Name and review required'});await initDb();await getDb().execute({sql:'INSERT INTO reviews(name,review,image,rating,created_at) VALUES(?,?,?,?,?)',args:[n,v,safe(image,1200),rate,now()]});res.json({ok:true})});app.delete('/api/admin/reviews/:id',async(req,res)=>{if(!auth(req))return res.status(401).end();await initDb();await getDb().execute({sql:'DELETE FROM reviews WHERE id=?',args:[Number(req.params.id)]});res.json({ok:true})});
const dist=path.join(root,'..','dist');app.use(express.static(dist));app.get('/admin',(_,res)=>res.sendFile(path.join(dist,'index.html')));app.get('/landing',(_,res)=>res.sendFile(path.join(dist,'index.html')));app.get('/{*splat}',(_,res)=>res.sendFile(path.join(dist,'index.html')));app.listen(process.env.PORT||10000);